.github/workflows/ci.yml, README.md, examples/custom_store.py, examples/dask_arr.py, examples/jax_arr.py, examples/numpy_arr.py, examples/pyopencl_arr.py, examples/sparse_arr.py, examples/tensorstore_arr.py, examples/torch_arr.py, examples/xarray_arr.py, examples/zarr_arr.py, pyproject.toml, src/ndv/__init__.py, src/ndv/data.py, src/ndv/util.py, src/ndv/viewer/_data_wrapper.py, src/ndv/viewer/_dims_slider.py, src/ndv/viewer/_save_button.py, src/ndv/viewer/_stack_viewer.py, src/ndv/viewer/_viewer.py, tests/conftest.py, tests/test_examples.py
- fixes some bugs
- adds `imshow()` convenience
- adds `ndv.data` convenience
- adds/extends support for more array types
- tests all examples
=> support more array types, add `imshow`

examples/tensorstore_arr.py, src/ndv/viewer/_data_wrapper.py
fixes a bug when indexing tensorstore
=> fix: tensorstore isel

src/ndv/viewer/_dims_slider.py
small fix to allow sliders to work on PySide6.  This is related to #30  ... but doesn't fully enable support yet.  Tests will still fail with either a segfault or a bus error, due to something going on with `ensure_main_thread`.  But this fix at least lets it be "usable" in pyside.  User will likely see a bus error on quit, or something like that.
=> fix: fix slider signals for pyside6

src/ndv/viewer/_backends/_pygfx.py, src/ndv/viewer/_viewer.py
This PR adds minor improvements to the PyGFX backend:
* Fixes the event filter, as previously events were not being captured, leading to the hover text not being updated.
* Implements `PyGFXViewerCanvas.canvas_to_world` (inspiration taken from pygfx/pygfx#745). Notably, there *seemed* to be a difference in assumptions between pixel centers between vispy and pygfx - we should decide whether we like the decision I made there.
=> Clean up PyGFX events

examples/zarr_arr.py, src/ndv/views/_vispy/_utils.py, src/ndv/views/_vispy/_vispy.py, tests/test_examples.py
this uses `texture_format='auto'` for gpus that support it. Which enables some of the calculations to be done on the GPU.  might speed up some stuff for @gselzer ?
=> feat: support GPU-calculated luts in vispy

examples/notebook.ipynb, src/ndv/views/_jupyter/_array_view.py, src/ndv/views/_wx/_array_view.py
=> refactor: Better Styles for wx and jupyter widgets

.github/workflows/deploy_docs.yml, docs/_overrides/main.html, mkdocs.yml
adds a notice to the docs for pre-release and dev builds:
=> docs: add pre-release banner

docs/js/install-table.js
Couple small fixes addressing part of the problem in #100:
* `jupyter_rfb` -> `jupyter-rfb`
* `glfw` -> `pyglfw` on jupyter
Additionally, extracted the commands for each source for a little DRYness. Arguably wasn't necessary and more could have been done, but the Boy Scout Rule was nagging me
=> docs: minor installation fixes & cleanup

.github/workflows/ci.yml, pyproject.toml, src/ndv/views/_app.py
should have done this before the release, but when I was making the conda recipe I noticed that we still depend on qtpy and superqt invariably.   We also don't have lower pins.  
I just tested a bunch of stuff to determine lower pins (can do this on CI later) and moved the qt extras into the qt-specific extras
=> chore: update dependencies

pyproject.toml
this adds lower and inner constrictions on pyqt6 and pyside6.  Note that we defer to superqt's pyside6 extra, which is a bit more nuanced: https://github.com/pyapp-kit/superqt/blob/646cb4ea48ca618eb2b9a44313000ea0892f8204/pyproject.toml#L79-L83
closes #59
=> build: restrict qt a bit more

src/ndv/views/_app.py, src/ndv/views/_jupyter/_app.py, src/ndv/views/_qt/_app.py, src/ndv/views/_wx/_app.py, src/ndv/views/bases/__init__.py, src/ndv/views/bases/_app.py
this is a bit of a reversal of #75 ... but probably much better than the state of things before #75.
basically: trying to get all the gui-specific stuff back into their own folders.  This creates a base NDVapp class that GUI frameworks have to implement to be supported.  (its the same as the current `GUIProvider` object).
it does move a little bit of logic for each framework *back* into `_app.py`, mostly the "is_running" logic.  but by having just that logic there, it allows all the rest to go back to the proper folder
this also fixes a bug wherein if you explicitly use `NDV_GUI_FRONTEND=qt` inside a jupyter notebook. it still doesn't let you use a Qt widget.
=> refactor: extract GUI-specific logic to GUI folders

pyproject.toml, src/ndv/views/_app.py, src/ndv/views/_pygfx/_histogram.py, tests/conftest.py, tests/test_controller.py
This is a repeat of #76, ready for eyes again.
There are a few problems I'm aware of, which I'm tempted just solve in separate PRs:
* There's "shimmering" when you pan/zoom the histogram canvas, due to aliasing. PyGFX's antialias solution of `renderer.pixel_ratio` was not sufficient to fix this on my machine.
* Note that the VisPy histogram also has this issue, but it is only seen when zooming.
* When you change the data, the pan/zoom resets. This is also a problem for the VisPy histogram.
=> Pygfx histogram v2

examples/README.md, examples/dask_arr.py, examples/notebook.ipynb, examples/numpy_arr.py, examples/pyopencl_arr.py, examples/sparse_arr.py, examples/tensorstore_arr.py, examples/torch_arr.py, examples/xarray_arr.py, examples/zarr_arr.py
This PR makes all of our examples [pep 723](https://peps.python.org/pep-0723/) compliant
which has the very cool side effect of support `uv run` and `pipx run`.  For example, to run the ndv tensorstore example, starting with *no* assumptions about the python version or environment installed on the users computer:
```sh
https://raw.githubusercontent.com/tlambert03/ndv/refs/heads/pep-723/examples/tensorstore_arr.py
```
=> docs: make all scripts pep 723 compliant

src/ndv/controllers/_array_viewer.py
fixes small avoidable bug when changing the channel mode combo box without data:
```
/Users/talley/dev/self/ndv/src/ndv/controllers/_array_viewer.py:328 in _on_view_channel_mode_changed
self._data_model.display.channel_mode = mode  # <-- SIGNAL WAS EMITTED HERE
CALLBACK CHAIN:
/Users/talley/dev/self/ndv/src/ndv/controllers/_array_viewer.py:279 in _on_model_channel_mode_changed
... 2 more frames ...
/Users/talley/dev/self/ndv/src/ndv/models/_data_display_model.py:104 in _ensure_wrapper
raise ValueError("Cannot normalize axes.  No data is set.")  # <-- ERROR OCCURRED HERE
```
=> fix: don't _update_visible_sliders if there is no data

.github/workflows/ci.yml
this particular combination always fails on CI.
=> test: skip ubuntu-vispy-pyside-3.12

src/ndv/views/__init__.py, src/ndv/views/_app.py, src/ndv/views/_qt/_app.py, src/ndv/views/_wx/_app.py, src/ndv/views/bases/_app.py
Something we generally need to be able to do in all gui frontends is call the equivalent of Qt's `QTimer.singleShot()` or `QApplication.processEvents()`.  this adds those two things to the App protocol, and exposes `ndv.call_later` (which is convenient for examples, and such)
=> feat: add `call_later` (public) and `process_events` (private) to the NDVApp API

src/ndv/controllers/_array_viewer.py, src/ndv/models/_viewer_model.py, src/ndv/views/_jupyter/_array_view.py, src/ndv/views/_qt/_array_view.py, src/ndv/views/_wx/_array_view.py, src/ndv/views/bases/_array_view.py, tests/conftest.py, tests/views/_jupyter/test_array_view.py, tests/views/_qt/conftest.py, tests/views/_qt/test_array_view.py, tests/views/_qt/test_lut_view.py, tests/views/_wx/test_array_view.py, tests/views/_wx/test_lut_view.py, uv.lock
In #134, I want to be able to reuse the ArrayView objects, but hide some of the widgets that aren't relevant in that context (such as the 3D button, and other widgets).  This PR adds various options to `ArrayViewerModel` that control the visibility of various elements:
```
show_3d_button: bool = True
show_histogram_button: bool = True
show_reset_zoom_button: bool = True
show_roi_button: bool = True
show_channel_mode_selector: bool = True
show_progress_spinner: bool = False
```
=> feat: add widget visibility options to ArrayViewerModel

src/ndv/views/_wx/_array_view.py
Closes #144 
We could consider adding tooltips here as well.
=> fix: Properly remove wx buttons labels

.github/workflows/ci.yml, pyproject.toml, uv.lock
With https://github.com/pyapp-kit/superqt/pull/283 in, I think our segfaults will be mostly fixed, so this PR ~removes the retries and simplifies ci.yml~
eh... looks like there are a couple residual sporadic segfaults.   so I'm going to leave in the retries.  this just repins superqt, and updates the setup-headless-display action
=> tests: update superqt to reduce segfaults

src/ndv/models/_data_wrapper.py
I was using `ndv` with `pymmcore-gui` and noticed this error while opening the histogram:
```
While emitting signal 'ndv.views._qt._array_view.QtArrayView.histogramRequested', an error occurred in a callback:
TypeError: Cannot interpret 'dtype("uint16")' as a data type
------------------------------------------------------------
SIGNAL EMISSION:
/Users/fdrgsp/Documents/git/pymmcore-gui/src/pymmcore_gui/_app.py:103 in main
app.exec()
/Users/fdrgsp/Documents/git/pymmcore-gui/.venv/lib/python3.12/site-packages/ndv/views/_qt/_array_view.py:253 in _on_q_histogram_toggled
self.histogramRequested.emit(self._channel)  # <-- SIGNAL WAS EMITTED HERE
CALLBACK CHAIN:
src/psygnal/_signal.py:1279 in _run_emit_loop
... 4 more frames ...
/Users/fdrgsp/Documents/git/pymmcore-gui/.venv/lib/python3.12/site-p …
```
=> fix: add tensorstore dtype property to tensorstore  DataWrapper

docs/js/install-table.js
I think our pyqt6 install method on conda is wrong... i think conda-forge still doesn't have pyqt6 (please anyone correct me if I'm wrong).  This updates the install page to clarify that it's just not available and to use pyside6 on conda
=> docs: clarify no pyqt6 on conda

src/ndv/models/_viewer_model.py, src/ndv/views/_qt/_array_view.py, tests/views/_qt/test_array_view.py
https://github.com/user-attachments/assets/1cda23ce-d4b1-4599-ad9a-78820fed92ea
=> feat: add back play button, as well as dimension size label

src/ndv/views/_qt/_array_view.py, src/ndv/views/_wx/_array_view.py, tests/views/_qt/test_lut_view.py, tests/views/_wx/test_lut_view.py
This PR adds GUI functionality for autoscaling using `ClimsPercentile`, where the user can ignore the outlier samples of the dataset being displayed in autoscale:
https://github.com/user-attachments/assets/3c832b83-904c-400e-b4f7-58cde99a412d
I like the placement as a context menu because it means all autoscaling functionality appears within the same area of the canvas and because it normally does not take up any screen space.
Unfortunately, I do not know whether this design is possible with all our frontends, seeing as how I cannot figure out how to write a context menu in ipywidgets.
We might instead have to settle for adding this widget to the layouts added in #146...
=> feat: Add autoscale tail ignore via popup

src/ndv/views/_pygfx/_histogram.py, src/ndv/views/_vispy/_plot_widget.py, tests/views/_pygfx/test_histogram.py, tests/views/_vispy/test_histogram.py
This PR enables panning histograms using horizontal scroll in both vispy and pygfx.
TODO:
Closes #172
=> Histogram hscroll pan

src/ndv/controllers/_array_viewer.py, src/ndv/views/_jupyter/_array_view.py, src/ndv/views/_qt/_array_view.py, src/ndv/views/_wx/_array_view.py, src/ndv/views/bases/_array_view.py, tests/test_controller.py, tests/views/_jupyter/test_array_view.py, tests/views/_qt/test_array_view.py, tests/views/_wx/test_array_view.py
The goal of this PR is to minimize the footprint of the `ArrayDataDisplayModel` by removing its usage within the `ArrayView`s. It is a potential alternative/complement to #184.
It turns out that the only reason the `ArrayDataDisplayModel` is being passed to the views is so that the array views could decide on the best dimension to visualize in the case we were moving from 2 dimensions to 3. I think this design is suboptimal as:
* It allows business logic in the views, when that logic should really be in the controller.
* That logic must be present in each `ArrayView` (i.e. it's WET)
The reason I hesitate with this change though is because I'd love a world where all views in NDV know about and operate directly on their associated models; this change goes against that by removing models …
=> feat: Purge ArrayDataDisplayModel from ArrayViews

src/ndv/controllers/_channel_controller.py, src/ndv/views/_wx/_array_view.py, tests/views/_wx/test_array_view.py
- Creates a scrollable area for LUTs
- Creates a multi-select to choose which LUTs go in the scrollable area
Resolves #193
=> Better gui for many channels (wx-specific)

src/ndv/controllers/_array_viewer.py, tests/test_controller.py
Closes #199.
We need to update the hover info whenever:
1. The user moves the mouse
2. The displayed data is updated under the mouse
Only the first case was previously covered.
To cover (2), we must keep track of the mouse position. Currently, this state is stored within the `ArrayViewer` and updated whenever (1) occurs. This state *could* potentially live in the `ArrayViewerModel` instead, if we find it helpful for other tasks.
=> fix: update hover on new data
